server:
  port: 10333
  
spring:
  data:
    mongodb:
      host: localhost 
      port: 0  #random port
      
#prettify the jspon output      
  jackson:
    serialization:
      indent-output: true 
      
logging:
  level:
    root: info
